### ISSUE TITLE
segment_coords grading bug? Endpoints are specified

### ISSUE THREAD

**Issue by dseaton** [open-craft/jsinput-vectordraw#18]
@antoviaque @mtyaka There may be an issue with segment_coords grading. From the docs:

* segment_coords: Just like coords, except that it is intented to be used with segments rather than vectors. Segments are not directed and there's no distinction between tail and tip points. - segment_coords: [[1, 2], [3, 4]] is therefore equivalent to segment_coords: [[3, 4], [1, 2]]. 

In my example [17 Draw Supply and Demand](https://github.com/open-craft/jsinput-vectordraw/tree/Daniel/Notes_and_Examples/17_SupplyDemand), segment coordinates are graded explicitly based on direction. 

See screenshot. The D curve is correct when drawn in the opposite direction (the label D at the bottom right), but incorrect in the screenshot.

![image](https://cloud.githubusercontent.com/assets/1703442/7948202/319e0432-0950-11e5-9eb6-dd8799edc1b1.png)

**Comment by mtyaka** [comment]
@dseaton I can confirm this bug, thanks for the example that demonstrates it. The fix is included among the changes in https://github.com/open-craft/jsinput-vectordraw/pull/19.

**Comment by mtyaka** [comment]
This is now fixed in master.

**Comment by dseaton** [comment]
@mtyaka Thanks! Example 17 is now working - and thank you for pushing the fix to all other examples. I am going to keep pushing drawing throughout the week - thanks again for your fast response!
